DROP TABLE BOARD;
DROP TABLE MEMBER;


CREATE TABLE MEMBER
(

	NO NUMBER,
	ID VARCHAR2(32) NOT NULL UNIQUE,
	PW VARCHAR2(32) NOT NULL,
	NAME VARCHAR2(50),
	EMAIL VARCHAR2(200) NOT NULL,
	REGDATE DATE


);
CREATE TABLE BOARD(
	ID NUMBER,
	AUTHOR VARCHAR2(50),
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000),
	HIT NUMBER,
	POSTDATE DATE


);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_PK PRIMARY KEY(NO);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_PK PRIMARY KEY(IDX);
ALTER TABLE BOARD ADD CONSTRAINT BOARD_MEMBER_FK FOREIGN KEY(AUTHOR) REFERENCES MEMBER(ID);

DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;


